// Single source of truth for SEO copy (per OSS_SPEC §11.3). Imported by
// runtime client code and by the post-build SEO splicer (which parses
// this file with a tiny regex reader, so keep the exported shapes
// simple: string literals, plain string arrays, and the routes table).

export const siteUrl = "https://zad.niclaslindstedt.se/";
export const siteName = "zad";
export const siteTagline =
  "Connect AI agents to external services without an MCP server";
export const siteDescription =
  "A Rust library and CLI that connects AI agents to Discord, Slack, Telegram, Google Calendar, Spotify, YouTube Music, and 1Password via signed, scoped TOML configs — no MCP server required.";

// Discoverability keywords. Targeted at programmers searching for any of:
//   - "rust mcp alternative", "rust agent tooling"
//   - "AI agent discord", "AI agent slack", "claude code discord"
//   - "discord cli rust", "slack cli rust", "telegram cli rust"
//   - "google calendar cli", "spotify cli", "1password cli alternative"
//   - "permission system AI", "scoped agent permissions"
// Update whenever the project picks up a new platform or use case so search
// engines have a fresh signal of what zad is for.
export const siteKeywords: string[] = [
  "rust",
  "rust cli",
  "rust library",
  "ai agents",
  "ai agent tools",
  "llm tools",
  "claude code",
  "claude tools",
  "mcp alternative",
  "no mcp server",
  "discord cli",
  "discord rust",
  "slack cli",
  "slack rust",
  "telegram cli",
  "telegram bot rust",
  "google calendar cli",
  "spotify cli",
  "youtube music cli",
  "1password cli",
  "agent permissions",
  "scoped permissions",
  "ed25519 signing",
  "toml config",
  "developer tools",
  "command line",
  "open source",
];

export const ogImage = `${siteUrl}og-default.png`;
export const ogImageWidth = 1200;
export const ogImageHeight = 630;

export const repoUrl = "https://github.com/niclaslindstedt/zad";
export const cratesCliUrl = "https://crates.io/crates/zad-cli";
export const cratesLibUrl = "https://crates.io/crates/zad";
export const issuesUrl = "https://github.com/niclaslindstedt/zad/issues";

export const author = "Niclas Lindstedt";
export const authorUrl = "https://niclaslindstedt.se";
export const applicationName = "zad";
export const language = "en";
export const themeColor = "#0b0f17";
export const twitterHandle = ""; // empty = omit twitter:site/twitter:creator

export interface RouteSeo {
  path: string;
  title: string;
  description: string;
  schemaType: "SoftwareApplication" | "TechArticle" | "CollectionPage";
}

// Static top-level routes the SPA serves. Per-page <head> for individual
// `/docs/<slug>` and `/manual/<slug>` entries is generated by the
// post-build splicer (it reads the `.md` files in `docs/` and `man/`
// directly, so adding a new doc or manpage is automatically indexed
// without editing this file).
export const routes: RouteSeo[] = [
  {
    path: "/",
    title: `${siteName} — ${siteTagline}`,
    description: siteDescription,
    schemaType: "SoftwareApplication",
  },
  {
    path: "/docs",
    title: `Documentation — ${siteName}: connect AI agents to Discord, Slack, Telegram & more`,
    description: `Hosted documentation for ${siteName}: getting started, configuration, architecture, services, and the permissions trust model. Covers Discord, Slack, Telegram, Google Calendar, Spotify, YouTube Music, and 1Password.`,
    schemaType: "CollectionPage",
  },
  {
    path: "/manual",
    title: `Manual — ${siteName} CLI command reference`,
    description: `Per-command reference for ${siteName}: every subcommand, flag, and environment variable the CLI accepts. Includes service lifecycle (create/enable/disable) and runtime verbs for every supported platform.`,
    schemaType: "CollectionPage",
  },
];
