//! Generic OAuth 2.0 loopback flow with PKCE.
//!
//! Used by every service whose credential shape is "OAuth 2.0
//! Authorization Code with PKCE": Google Calendar, Spotify, and any
//! future provider with the same flow. Provider-specific knobs
//! (endpoints, scopes, public-client vs. confidential client, extra
//! query params like Google's `prompt=consent` or Spotify's
//! `show_dialog`) are threaded in via [`LoopbackConfig`].
//!
//! ## Security properties
//!
//! - **PKCE S256** — the verifier is a 64-byte random string; the
//!   challenge is its URL-safe base64-encoded SHA-256.
//! - **State parameter** — a 32-byte random token is encoded into the
//!   auth URL and verified on the callback. Prevents a co-resident
//!   process from racing the browser to the loopback port with a
//!   forged `code`.
//! - **`127.0.0.1` listener** (not `localhost`) — matches Google's
//!   current redirect-URI guidance and sidesteps browsers that refuse
//!   `http://localhost` redirects. Spotify also accepts this form.
//! - **Per-service scheme** — gcal stays on `http://127.0.0.1:<port>`;
//!   Spotify (which dropped HTTP for OAuth redirects) uses
//!   `https://127.0.0.1:<port>` and we terminate TLS in-process with a
//!   per-session self-signed cert generated by `rcgen`. The browser
//!   shows a "connection not private" warning the operator clicks
//!   through once per flow — the certificate never leaves the box.
//! - **Prefetch-tolerant listener** — accepts only the first request
//!   whose path carries `?code=` or `?error=`; probes (favicon, DNS
//!   prefetch, HEAD) get a 404 and the listener keeps waiting.
//! - **Deadline** — overall 120 s budget (configurable via
//!   [`LoopbackConfig::timeout`]); a hung browser can't block the CLI
//!   forever.
//!
//! ## Failure modes the call-site should surface clearly
//!
//! - `redirect_uri_mismatch` on token exchange → the registered
//!   redirect URI on the OAuth client does not include the loopback
//!   form the service uses (`http://127.0.0.1` for gcal,
//!   `https://127.0.0.1` for Spotify). The error message points at
//!   the per-service manpage for the exact URI to register.
//! - `invalid_grant` on token exchange → the refresh token was
//!   revoked at the provider, or clock skew on the local machine.
//! - Port-bind failure → another process is holding port 0 (extremely
//!   rare); surface the error as a plain I/O error.

use std::io::{BufRead, BufReader, Read, Write};
use std::net::{TcpListener, TcpStream};
use std::sync::Arc;
use std::time::{Duration, Instant};

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use rand::RngCore;
use rustls::ServerConfig;
use rustls::pki_types::{CertificateDer, PrivateKeyDer, PrivatePkcs8KeyDer};
use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::error::{Result, ZadError};

/// Endpoints + client identity the loopback flow needs.
#[derive(Debug, Clone)]
pub struct LoopbackConfig {
    /// Lowercase zad service name (`"gcal"`, `"spotify"`, …). Used as
    /// the `name` field on `ZadError::Service` errors emitted by the
    /// helper so a caller's error mapping doesn't have to wrap them.
    pub service_name: &'static str,
    /// Capitalized display name (`"Google Calendar"`, `"Spotify"`).
    /// Surfaces in the interactive prompt printed before the browser
    /// opens, and in the success / failure HTML rendered to the
    /// browser tab.
    pub display_name: &'static str,
    /// OAuth 2.0 authorization endpoint, e.g.
    /// `https://accounts.google.com/o/oauth2/v2/auth` or
    /// `https://accounts.spotify.com/authorize`.
    pub auth_url: String,
    /// OAuth 2.0 token endpoint, e.g.
    /// `https://oauth2.googleapis.com/token` or
    /// `https://accounts.spotify.com/api/token`.
    pub token_url: String,
    /// Pre-registered OAuth client ID (non-secret).
    pub client_id: String,
    /// OAuth client secret. Google's "Desktop app" client type still
    /// issues one even though it's not strictly secret in the spec
    /// sense — we forward it verbatim to the token endpoint. `None`
    /// for PKCE-only public clients (e.g. Spotify) where the token
    /// endpoint must not receive a `client_secret` form field at all.
    pub client_secret: Option<String>,
    /// Provider scopes (space-joined in the auth URL).
    pub scopes: Vec<String>,
    /// Extra provider-specific query params to splice into the
    /// authorization URL (e.g. Google's `access_type=offline` /
    /// `prompt=consent` / `include_granted_scopes=true`, or Spotify's
    /// `show_dialog=true`). Standard params (`client_id`,
    /// `redirect_uri`, `response_type`, `scope`, `state`,
    /// `code_challenge`, `code_challenge_method`) are always emitted by
    /// the helper itself — don't list them here.
    pub extra_auth_params: Vec<(String, String)>,
    /// How long to wait for the browser callback before giving up.
    pub timeout: Duration,
    /// Scheme to use for the loopback redirect URI. Defaults to
    /// `Http` to match RFC 8252 loopback guidance and the historical
    /// behaviour. Set to `Https` for providers that no longer accept
    /// plain-HTTP loopback URIs (Spotify); the helper then terminates
    /// TLS on the loopback listener with a per-session self-signed
    /// certificate.
    pub redirect_scheme: RedirectScheme,
}

/// Scheme used for the loopback `redirect_uri` value sent to the
/// authorization endpoint and bound on the local listener.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum RedirectScheme {
    #[default]
    Http,
    Https,
}

impl RedirectScheme {
    /// URL-scheme prefix written into the `redirect_uri` query
    /// parameter (and bound on the local listener).
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Http => "http",
            Self::Https => "https",
        }
    }
}

impl Default for LoopbackConfig {
    fn default() -> Self {
        Self {
            service_name: "",
            display_name: "",
            auth_url: String::new(),
            token_url: String::new(),
            client_id: String::new(),
            client_secret: None,
            scopes: Vec::new(),
            extra_auth_params: Vec::new(),
            timeout: Duration::from_secs(120),
            redirect_scheme: RedirectScheme::Http,
        }
    }
}

/// What the caller gets back on a successful exchange.
#[derive(Debug, Clone)]
pub struct TokenSet {
    pub access_token: String,
    /// Some providers (Google) only issue refresh tokens when
    /// `access_type=offline` is set **and** the user has consented;
    /// otherwise the server omits the field entirely. We surface
    /// `Option` so the caller can produce a useful error pointing at
    /// the missing knob.
    pub refresh_token: Option<String>,
    /// Seconds until `access_token` expires. Informational only; the
    /// CLI refetches on every invocation instead of persisting this.
    pub expires_in: Option<u64>,
    /// OpenID token when the `openid` scope was requested. Contains a
    /// JWT we don't parse locally — a separate userinfo call is the
    /// source of truth for the authenticated identity.
    pub id_token: Option<String>,
}

/// The full interactive flow: spin up a loopback listener, build the
/// auth URL, return its text so the caller can print/open it, then
/// wait for the callback, verify state, exchange code for tokens.
///
/// `open_browser` is honoured here — we call [`open::that`] when
/// `true` and the caller can still print the URL regardless.
pub async fn run_loopback_flow(cfg: &LoopbackConfig, open_browser: bool) -> Result<TokenSet> {
    let listener = TcpListener::bind("127.0.0.1:0").map_err(|e| {
        ZadError::Invalid(format!(
            "could not bind 127.0.0.1 loopback listener for OAuth: {e}"
        ))
    })?;
    let port = listener
        .local_addr()
        .map_err(|e| ZadError::Invalid(format!("loopback listener has no local address: {e}")))?
        .port();

    let pkce = Pkce::new();
    let state = random_url_safe(32);
    let redirect_uri = format!("{}://127.0.0.1:{port}", cfg.redirect_scheme.as_str());

    let tls_cfg = match cfg.redirect_scheme {
        RedirectScheme::Http => None,
        RedirectScheme::Https => Some(build_tls_server_config()?),
    };

    let auth_url = build_auth_url(cfg, &redirect_uri, &pkce.challenge, &state);

    println!();
    println!(
        "Opening your browser to authorize zad with {}:",
        cfg.display_name
    );
    println!("  {auth_url}");
    println!();
    println!("Waiting up to {}s for the redirect…", cfg.timeout.as_secs());
    if matches!(cfg.redirect_scheme, RedirectScheme::Https) {
        println!(
            "Note: the loopback callback uses a self-signed TLS cert — your browser will \
             show a \"connection not private\" warning. Click through it to finish authorization."
        );
    }
    if open_browser {
        let _ = open::that(&auth_url);
    }

    let callback = accept_callback(&listener, tls_cfg.as_ref(), cfg.timeout, cfg.display_name)?;
    if callback.state != state {
        return Err(ZadError::Invalid(
            "OAuth callback returned a state value that doesn't match the one we sent; \
             refusing to continue (possible CSRF attempt)"
                .into(),
        ));
    }
    let code = callback.code.ok_or_else(|| match callback.error {
        Some(e) => ZadError::Service {
            name: cfg.service_name,
            message: format!("OAuth authorization failed: {e}"),
        },
        None => ZadError::Invalid(
            "OAuth callback carried neither `code` nor `error` — cannot continue".into(),
        ),
    })?;

    exchange_code(cfg, &redirect_uri, &code, &pkce.verifier).await
}

/// Persist a rotated refresh token.
///
/// Some OAuth providers (notably Spotify's PKCE flow) issue a fresh
/// `refresh_token` on every `/api/token` call and revoke the previous
/// one after a short grace window. Service HTTP clients call
/// [`Self::store`] whenever the response carries a `refresh_token`
/// that differs from the one they sent, so the next process picks up
/// the rotated value instead of replaying a token Spotify is about to
/// revoke.
///
/// Implementations decide where the token lives. The default zad
/// layout uses [`KeychainRefreshStore`] to write into the OS keychain;
/// library users with a different storage backend supply their own
/// impl. Errors propagate up to the caller — silently swallowing them
/// recreates the very bug this trait exists to prevent.
pub trait RefreshTokenStore: Send + Sync {
    fn store(&self, refresh_token: &str) -> Result<()>;
}

/// Default [`RefreshTokenStore`] that writes the rotated token into
/// the OS keychain via [`crate::secrets::store`].
///
/// Built from the canonical zad keychain account string, e.g.
/// `secrets::account("spotify", "refresh", Scope::Global)` — the same
/// slot the lifecycle path (`zad service create spotify`) writes the
/// initial token to, so subsequent `from_default_config` consumers
/// pick up the rotated value automatically.
pub struct KeychainRefreshStore {
    account: String,
}

impl KeychainRefreshStore {
    pub fn new(account: impl Into<String>) -> Self {
        Self {
            account: account.into(),
        }
    }
}

impl RefreshTokenStore for KeychainRefreshStore {
    fn store(&self, refresh_token: &str) -> Result<()> {
        crate::secrets::store(&self.account, refresh_token)
    }
}

/// Exchange a refresh token for a fresh access token. Called on every
/// CLI run — we never persist access tokens. Pass `None` for
/// `client_secret` when the OAuth client is a PKCE-only public client
/// (e.g. Spotify) — the token endpoint must not receive a
/// `client_secret` form field at all in that case. `service_name` is
/// the lowercase zad service name; it labels the `ZadError::Service`
/// errors emitted from this function.
pub async fn refresh_access_token(
    service_name: &'static str,
    token_url: &str,
    client_id: &str,
    client_secret: Option<&str>,
    refresh_token: &str,
) -> Result<TokenSet> {
    let mut params: Vec<(&str, &str)> = vec![
        ("client_id", client_id),
        ("refresh_token", refresh_token),
        ("grant_type", "refresh_token"),
    ];
    if let Some(secret) = client_secret {
        params.push(("client_secret", secret));
    }
    post_token_endpoint(service_name, token_url, &params).await
}

/// Build the OAuth 2.0 authorization URL. Exposed publicly so
/// per-service URL tests can reconstruct and verify it without
/// running the full flow.
pub fn build_auth_url(
    cfg: &LoopbackConfig,
    redirect_uri: &str,
    code_challenge: &str,
    state: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&cfg.auth_url);
    let mut first = true;
    let mut push_param = |key: &str, value: &str, first: &mut bool| {
        out.push(if *first { '?' } else { '&' });
        *first = false;
        out.push_str(key);
        out.push('=');
        out.push_str(&urlencode(value));
    };
    push_param("client_id", &cfg.client_id, &mut first);
    push_param("redirect_uri", redirect_uri, &mut first);
    push_param("response_type", "code", &mut first);
    push_param("scope", &cfg.scopes.join(" "), &mut first);
    push_param("state", state, &mut first);
    push_param("code_challenge", code_challenge, &mut first);
    push_param("code_challenge_method", "S256", &mut first);
    for (k, v) in &cfg.extra_auth_params {
        push_param(k, v, &mut first);
    }
    out
}

/// PKCE verifier + challenge pair. The verifier is kept around until
/// token exchange; the challenge is what we put in the auth URL.
#[derive(Debug, Clone)]
pub(crate) struct Pkce {
    pub verifier: String,
    pub challenge: String,
}

impl Pkce {
    pub(crate) fn new() -> Self {
        // 64 bytes → ~86 chars after URL-safe base64; spec range is
        // 43..=128 chars and every provider we target accepts that
        // length.
        let verifier = random_url_safe(64);
        let mut hasher = Sha256::new();
        hasher.update(verifier.as_bytes());
        let digest = hasher.finalize();
        let challenge = URL_SAFE_NO_PAD.encode(digest);
        Self {
            verifier,
            challenge,
        }
    }
}

/// Cryptographically-random URL-safe string of approximately `bytes`
/// bytes of entropy.
pub(crate) fn random_url_safe(bytes: usize) -> String {
    let mut buf = vec![0u8; bytes];
    rand::thread_rng().fill_bytes(&mut buf);
    URL_SAFE_NO_PAD.encode(buf)
}

/// Minimal percent-encoding — the RFC3986 unreserved set plus a few
/// practical safe chars. Pulled in here to avoid a whole-crate
/// dependency on `percent-encoding` / `url` for one tiny helper.
fn urlencode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'0'..=b'9' | b'A'..=b'Z' | b'a'..=b'z' | b'-' | b'.' | b'_' | b'~' => {
                out.push(b as char)
            }
            _ => out.push_str(&format!("%{b:02X}")),
        }
    }
    out
}

#[derive(Debug, Clone, Default)]
struct Callback {
    code: Option<String>,
    state: String,
    error: Option<String>,
}

/// Accept connections until we see the real OAuth redirect or hit the
/// deadline. Non-callback requests (favicon, HEAD probes, DNS
/// prefetch) get a 404 and the loop continues. When `tls_cfg` is
/// `Some`, every accepted TCP stream is wrapped in a sync rustls
/// server stream before being handed to the request handler.
fn accept_callback(
    listener: &TcpListener,
    tls_cfg: Option<&Arc<ServerConfig>>,
    timeout: Duration,
    display_name: &str,
) -> Result<Callback> {
    listener
        .set_nonblocking(true)
        .map_err(|e| ZadError::Invalid(format!("could not configure loopback listener: {e}")))?;

    let deadline = Instant::now() + timeout;
    loop {
        if Instant::now() >= deadline {
            return Err(ZadError::Invalid(format!(
                "timed out after {}s waiting for the OAuth callback",
                timeout.as_secs()
            )));
        }
        match listener.accept() {
            Ok((tcp, _addr)) => {
                tcp.set_nonblocking(false).map_err(|e| {
                    ZadError::Invalid(format!("loopback set_nonblocking(false) failed: {e}"))
                })?;
                tcp.set_read_timeout(Some(Duration::from_secs(5)))
                    .map_err(|e| {
                        ZadError::Invalid(format!("loopback read-timeout set failed: {e}"))
                    })?;
                let result = match tls_cfg {
                    None => handle_one(&mut PlainStream(tcp), display_name)?,
                    Some(cfg) => match rustls::ServerConnection::new(cfg.clone()) {
                        Ok(conn) => {
                            let mut stream = rustls::StreamOwned::new(conn, tcp);
                            handle_one(&mut stream, display_name)?
                        }
                        Err(_) => continue,
                    },
                };
                if let Some(cb) = result {
                    return Ok(cb);
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                std::thread::sleep(Duration::from_millis(50));
            }
            Err(e) => {
                return Err(ZadError::Invalid(format!(
                    "loopback listener accept failed: {e}"
                )));
            }
        }
    }
}

/// Newtype wrapper so the plain HTTP path satisfies the same
/// `Read + Write` bound as the rustls TLS stream. `TcpStream` itself
/// only impls those traits via auto-ref tricks that don't work
/// through a generic bound.
struct PlainStream(TcpStream);

impl Read for PlainStream {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        self.0.read(buf)
    }
}

impl Write for PlainStream {
    fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
        self.0.write(buf)
    }
    fn flush(&mut self) -> std::io::Result<()> {
        self.0.flush()
    }
}

fn handle_one<S: Read + Write>(stream: &mut S, display_name: &str) -> Result<Option<Callback>> {
    // Read just the request line — we don't need headers or body.
    let mut request_line = String::new();
    {
        let mut reader = BufReader::new(&mut *stream);
        if reader.read_line(&mut request_line).is_err() {
            return Ok(None);
        }
    }
    // Drain whatever's still buffered (request headers) so the
    // remote side sees a clean response/close.
    let mut scratch = [0u8; 1024];
    let _ = stream.read(&mut scratch);

    // Request line looks like: `GET /?code=…&state=… HTTP/1.1\r\n`
    let mut parts = request_line.split_whitespace();
    let _method = parts.next();
    let path = parts.next().unwrap_or("");

    // Anything without a `code=` or `error=` query is a probe.
    if !path.contains("code=") && !path.contains("error=") {
        let _ = write_response(stream, 404, "text/plain", b"not found");
        return Ok(None);
    }

    let cb = parse_callback_query(path);
    let body = if cb.code.is_some() {
        b"<!doctype html><html><body style='font-family:system-ui'>\
          <h2>zad: authorization complete</h2>\
          <p>You can close this tab and return to the terminal.</p>\
          </body></html>"
            .to_vec()
    } else {
        let err = cb.error.as_deref().unwrap_or("unknown");
        format!(
            "<!doctype html><html><body style='font-family:system-ui'>\
             <h2>zad: authorization failed</h2>\
             <p>{display_name} reported: <code>{err}</code></p>\
             <p>Return to the terminal for details.</p></body></html>"
        )
        .into_bytes()
    };
    let _ = write_response(stream, 200, "text/html; charset=utf-8", &body);
    Ok(Some(cb))
}

fn write_response<W: Write>(
    stream: &mut W,
    status: u16,
    content_type: &str,
    body: &[u8],
) -> std::io::Result<()> {
    let status_line = match status {
        200 => "200 OK",
        _ => "404 Not Found",
    };
    let headers = format!(
        "HTTP/1.1 {status_line}\r\nContent-Type: {content_type}\r\n\
         Content-Length: {}\r\nConnection: close\r\n\r\n",
        body.len()
    );
    stream.write_all(headers.as_bytes())?;
    stream.write_all(body)?;
    stream.flush()
}

/// Build a `rustls::ServerConfig` backed by a fresh self-signed
/// certificate covering `127.0.0.1` and `localhost`. The cert is
/// regenerated on every flow — it never touches disk.
fn build_tls_server_config() -> Result<Arc<ServerConfig>> {
    // rustls 0.23 requires a crypto provider to be installed before
    // any builder is used. `install_default` returns Err when one is
    // already installed (e.g. by reqwest in the same process); ignore
    // that case.
    let _ = rustls::crypto::ring::default_provider().install_default();

    let alt_names = vec!["127.0.0.1".to_string(), "localhost".to_string()];
    let rcgen::CertifiedKey { cert, key_pair } = rcgen::generate_simple_self_signed(alt_names)
        .map_err(|e| {
            ZadError::Invalid(format!("could not generate loopback TLS certificate: {e}"))
        })?;

    let cert_der: CertificateDer<'static> = cert.der().clone();
    let key_der: PrivateKeyDer<'static> = PrivatePkcs8KeyDer::from(key_pair.serialize_der()).into();

    let server_cfg = ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(vec![cert_der], key_der)
        .map_err(|e| {
            ZadError::Invalid(format!("could not build loopback TLS server config: {e}"))
        })?;

    Ok(Arc::new(server_cfg))
}

fn parse_callback_query(path: &str) -> Callback {
    let query = path.split_once('?').map(|(_, q)| q).unwrap_or("");
    let mut out = Callback::default();
    for pair in query.split('&') {
        let Some((k, v)) = pair.split_once('=') else {
            continue;
        };
        let decoded = urldecode(v);
        match k {
            "code" => out.code = Some(decoded),
            "state" => out.state = decoded,
            "error" => out.error = Some(decoded),
            _ => {}
        }
    }
    out
}

fn urldecode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let bytes = s.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'+' => {
                out.push(' ');
                i += 1;
            }
            b'%' if i + 2 < bytes.len() => {
                let hex = std::str::from_utf8(&bytes[i + 1..i + 3]).unwrap_or("00");
                let val = u8::from_str_radix(hex, 16).unwrap_or(0);
                out.push(val as char);
                i += 3;
            }
            b => {
                out.push(b as char);
                i += 1;
            }
        }
    }
    out
}

async fn exchange_code(
    cfg: &LoopbackConfig,
    redirect_uri: &str,
    code: &str,
    verifier: &str,
) -> Result<TokenSet> {
    let mut params: Vec<(&str, &str)> = vec![
        ("client_id", cfg.client_id.as_str()),
        ("code", code),
        ("code_verifier", verifier),
        ("grant_type", "authorization_code"),
        ("redirect_uri", redirect_uri),
    ];
    if let Some(secret) = cfg.client_secret.as_deref() {
        params.push(("client_secret", secret));
    }
    post_token_endpoint(cfg.service_name, &cfg.token_url, &params).await
}

#[derive(Debug, Deserialize)]
struct RawTokenResponse {
    access_token: Option<String>,
    refresh_token: Option<String>,
    expires_in: Option<u64>,
    id_token: Option<String>,
    error: Option<String>,
    error_description: Option<String>,
}

async fn post_token_endpoint(
    service_name: &'static str,
    url: &str,
    form: &[(&str, &str)],
) -> Result<TokenSet> {
    let resp = reqwest::Client::new()
        .post(url)
        .form(form)
        .send()
        .await
        .map_err(|e| ZadError::Service {
            name: service_name,
            message: format!("network error talking to OAuth endpoint: {e}"),
        })?;
    let status = resp.status();
    let body = resp.text().await.map_err(|e| ZadError::Service {
        name: service_name,
        message: format!("failed to read OAuth response body: {e}"),
    })?;

    let parsed: RawTokenResponse = serde_json::from_str(&body).map_err(|e| ZadError::Service {
        name: service_name,
        message: format!("failed to decode OAuth response (HTTP {status}): {e}; body: {body}"),
    })?;

    if let Some(err) = parsed.error {
        let desc = parsed
            .error_description
            .as_deref()
            .unwrap_or("no description provided");
        // `invalid_grant` specifically means the refresh token was
        // revoked at the provider — surface with a pointer to re-run
        // create so the operator isn't left guessing.
        if err == "invalid_grant" {
            return Err(ZadError::Service {
                name: service_name,
                message: format!(
                    "refresh token is no longer valid ({desc}); re-run `zad service create {service_name}`"
                ),
            });
        }
        if err == "redirect_uri_mismatch" {
            return Err(ZadError::Service {
                name: service_name,
                message: format!(
                    "OAuth provider rejected the loopback redirect URI ({desc}). \
                     Verify the OAuth client's allowed redirect URIs match the loopback form \
                     this service expects — see `zad man {service_name}` for the exact URI \
                     to register."
                ),
            });
        }
        return Err(ZadError::Service {
            name: service_name,
            message: format!("OAuth error `{err}`: {desc}"),
        });
    }

    let access_token = parsed.access_token.ok_or(ZadError::Service {
        name: service_name,
        message: "OAuth response contained no access_token".into(),
    })?;

    Ok(TokenSet {
        access_token,
        refresh_token: parsed.refresh_token,
        expires_in: parsed.expires_in,
        id_token: parsed.id_token,
    })
}
